### ISSUE TITLE
.NET 8 LTS build breaks

### ISSUE THREAD

**Issue by fasteddys** [axuno/TournamentCalendar#53]
Hello can you help with the build update, my laptop shipped with 8 LTS

**Comment by axunonb** [comment]
We will migrate to net8, but not with high priority.
If your PC is missing net6, just download the SDK from Microsoft and you're good to go.

**Comment by axunonb** [comment]
The project is migrated to net8.0 in [v4.0.0](https://github.com/axuno/TournamentCalendar/releases/tag/v4.0.0)
